# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/goldenve/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/goldenve/proprietary/sys/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/goldenve/proprietary/sys/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/goldenve/proprietary/sys/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/goldenve/proprietary/sys/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libxml2.so:system/lib/libxml2.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio_policy.mrvl.so:system/lib/hw/audio_policy.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libaudiodebugtool.so:system/lib/libaudiodebugtool.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/goldenve/proprietary/sys/lib/soundfx/libmrvlpreprocessing.so:system/lib/soundfx/libmrvlpreprocessing.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libnvaccessor_fb.so:system/lib/libnvaccessor_fb.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libsocketsvr.so:system/lib/libsocketsvr.so \
    vendor/samsung/goldenve/proprietary/sys/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/goldenve/proprietary/sys/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/goldenve/proprietary/sys/etc/common_scene_tuning.data:system/etc/common_scene_tuning.data \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcoda7542hal.so:system/lib/libcoda7542hal.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcoda7542.so:system/lib/libcoda7542.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodeccoda7542dec.so:system/lib/libcodeccoda7542dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodeccoda7542enc.so:system/lib/libcodeccoda7542enc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecpngdec.so:system/lib/libcodecpngdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcpufreqinterface.so:system/lib/libcpufreqinterface.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libcpufreq.so:system/lib/libcpufreq.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/goldenve/proprietary/sys/etc/AGPS_CA.pem:system/etc/AGPS_CA.pem \
    vendor/samsung/goldenve/proprietary/sys/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/goldenve/proprietary/sys/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    vendor/samsung/goldenve/proprietary/sys/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
    vendor/samsung/goldenve/proprietary/sys/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/goldenve/proprietary/sys/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/samsung/goldenve/proprietary/sys/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so \
    vendor/samsung/goldenve/proprietary/sys/vendor/firmware/libpn547_fw_pku.so:system/vendor/firmware/libpn547_fw_pku.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/nfc.PXA986.so:system/lib/hw/nfc.PXA986.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libsimal.so:system/lib/libsimal.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libserialport.so:system/lib/libserialport.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libceu.so:system/lib/libceu.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/goldenve/proprietary/sys/lib/librtp_jni.so:system/lib/librtp_jni.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libacm.so:system/lib/libacm.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libAndroidEvent.so:system/lib/libAndroidEvent.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libippimgp.so:system/lib/libippimgp.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libippsp.so:system/lib/libippsp.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libippvp.so:system/lib/libippvp.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libOrgan.so:system/lib/libOrgan.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libPowerSetting.so:system/lib/libPowerSetting.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libparseTim.so:system/lib/libparseTim.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/vendor/lib/hw/lights.mrvl.so:system/vendor/lib/hw/lights.mrvl.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/goldenve/proprietary/sys/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/goldenve/proprietary/sys/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/goldenve/proprietary/sys/lib/drm/libplayreadyplugin.so:system/lib/drm/libplayreadyplugin.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/goldenve/proprietary/sys/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so
